# Generated by Django 5.0.7 on 2024-12-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="switch_datalist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_type", models.CharField(max_length=32, verbose_name="设备类型")),
                ("currentA", models.SmallIntegerField(verbose_name="开关A相电流")),
                ("currentB", models.SmallIntegerField(verbose_name="开关B相电流")),
                ("currentC", models.SmallIntegerField(verbose_name="开关C相电流")),
                ("angle", models.SmallIntegerField(verbose_name="开关转动角度")),
                ("torque", models.SmallIntegerField(verbose_name="开关主轴扭矩")),
                ("add_time", models.DateTimeField(max_length=32, verbose_name="录入时间")),
            ],
        ),
    ]
