# Generated by Django 5.0.7 on 2024-12-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="switch_datalist",
            name="device_type",
            field=models.SmallIntegerField(default=1, verbose_name="设备类型"),
        ),
    ]
