# Generated by Django 5.0.7 on 2024-12-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0002_alter_switch_datalist_device_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="switch_datalist",
            name="device_type",
            field=models.SmallIntegerField(
                choices=[(1, "隔离开关"),],
                default=1,
                verbose_name="设备类型",
            ),
        ),
    ]
