# Generated by Django 5.0.7 on 2024-12-27 18:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0003_alter_switch_datalist_device_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Userlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=32, verbose_name="用户名")),
                ("user_phone", models.CharField(max_length=32, verbose_name="手机号码")),
                ("user_mail", models.CharField(max_length=32, verbose_name="注册邮箱")),
                ("user_password", models.CharField(max_length=32, verbose_name="密码")),
            ],
        ),
    ]
