# Generated by Django 5.0.7 on 2025-01-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0004_userlist"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sys_log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.SmallIntegerField(
                        choices=[
                            (1, "隔离开关运行数据添加"),
                            (2, "隔离开关运行数据修改"),
                            (3, "用户数据修改"),
                            (4, "用户数据删除"),
                        ],
                        default=1,
                        verbose_name="事件类型",
                    ),
                ),
                ("user_name", models.CharField(max_length=32, verbose_name="用户名")),
                ("user_phone", models.CharField(max_length=32, verbose_name="手机号码")),
                (
                    "record_time",
                    models.DateTimeField(max_length=32, verbose_name="录入时间"),
                ),
            ],
        ),
    ]
