# Generated by Django 5.0.7 on 2025-01-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0006_alter_sys_log_event_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sys_log",
            name="event_type",
            field=models.SmallIntegerField(
                choices=[
                    (1, "隔离开关运行数据添加"),
                    (2, "隔离开关运行数据修改"),
                    (3, "隔离开关运行数据删除"),
                    (4, "用户信息修改"),
                    (5, "用户数据删除"),
                    (6, "用户密码重置"),
                ],
                default=1,
                verbose_name="事件类型",
            ),
        ),
    ]
