# Generated by Django 5.0.7 on 2025-02-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0008_alter_sys_log_event_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="userlist",
            name="last_pwd_changed",
            field=models.DateTimeField(blank=True, null=True, verbose_name="密码修改时间"),
        ),
    ]
