# Generated by Django 5.1.3 on 2025-03-28 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0009_userlist_last_pwd_changed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="switch_datalist",
            name="device_type",
            field=models.SmallIntegerField(
                choices=[(1, "隔离开关")], default=1, verbose_name="设备类型"
            ),
        ),
        migrations.AlterField(
            model_name="sys_log",
            name="event_type",
            field=models.SmallIntegerField(
                choices=[
                    (1, "隔离开关运行数据添加"),
                    (2, "隔离开关运行数据修改"),
                    (3, "隔离开关运行数据删除"),
                    (4, "用户信息修改"),
                    (5, "用户账号删除"),
                    (6, "用户密码重置"),
                ],
                default=1,
                verbose_name="事件类型",
            ),
        ),
    ]
